### ISSUE TITLE
About tap trigger twice

### ISSUE THREAD

**Issue by deveploer** [cubiq/iscroll#1003]
I met a problem, I have a lot of buttons on a page, when I click on the button will pop up modal box, but the modal dialog just above the button, the button to trigger the second click trigger to the inside of the modal dialog button, is there any way to solve this problem

**Comment by sculove** [comment]
I forked iscroll 5.1.3
https://github.com/naver/egscroll

egscroll fix this issue.

**Comment by sculove** [comment]
I merged 6b19e828b1f16be0b324289381d2ead82033aa37
