### ISSUE TITLE
Why iScroll 5 works only after rotating to landscape and back to portrait on Mobile Web

### ISSUE THREAD

**Issue by onlinerahul** [cubiq/iscroll#1005]
I am developing a mobile web app using AngularJs and i m using Iscroll (http://cubiq.org/iscroll-5) having a issue is that when I test on actual mobile device iPhone 5s and android  only Scrollbar starts after orientation was change, with out orientation change it will behave like rubber band.

Your immediate response is highly appreciated!

I am using:

function loaded () {
 
	myScroll = new IScroll('#wrapper', {
		scrollbars: true,
		checkDOMChanges: false,
		mouseWheel: true,
		interactiveScrollbars: true,
		shrinkScrollbars: 'scale',
		fadeScrollbars: true
	})

		setTimeout(function(){
                        myScroll.refresh();
                        console.log('myScroll')
                    }, 2000);
 
}

Please help!

**Comment by glebmachine** [comment]
Hi!

Where you call this loaded function?
Try following:
 - Make sure iscroll inited after DOM node become visible
 - Try to initiate iscroll from DevTool console. Still need to resize/orientationchange?

Can i have a url to check?

**Comment by onlinerahul** [comment]
Hello, 

Many Thanks for your reply.

I am not sure, whats the issue, i checked on browserstack.com was working fine but on actual device i am facing this issue with combination of Iphone 

But still iScroll works when I make a portrait-landscape-portrait flip. How can I fix this ? Or debug the problem.

Scrolling doesn't work when the page loaded. iScroll works when I flip device to landscape and then back to portrait. 

<script type="text/javascript" src="/scripts/iscroll.js"></script>
<body onload="loaded()">
 <div id="wrapper">
	<div id="scroller">
	     <div>...</div>
	 </div>
        </div>
</body>

I added viewport:
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

I added a timeout like this:

 setTimeout(function(){
                    myScroll.refresh();
                    console.log('myScroll')
                }, 2000);


Thanks
Rahul

**Comment by glebmachine** [comment]
Looks weird, can you test on real iphone4/5?

**Comment by onlinerahul** [comment]
Yes, I have tested on real iphone4/5? has same this core issue but if i test on emulator on browserstack.com it works fine. is there anyway to fix this issue, i am struggling around for the last one week, getting this weird behavior defects,

**Comment by glebmachine** [comment]
Got it, looks like race condition.
Let me have a look, can you share url?

**Comment by onlinerahul** [comment]
Hello,
I cant able to provide URL at the moment, because we are working on banking domain and it's bit confidential, hope you understand, however i would request if you provide any live example I'll implement and let you know.

**Comment by onlinerahul** [comment]
Hey Gleb, Any Fix for that?

**Comment by glebmachine** [comment]
I have answered you by email)
