### ISSUE TITLE
Pointer events struggle on Windows Phone 10

### ISSUE THREAD

**Issue by vvanghelue** [cubiq/iscroll#1009]
Scrolling does not work on Windows Phone 10 (Windows Phone 8 OK). Pointer events and touch events seems to not cascade the same way on WP10.

Hot fix :
https://github.com/Mappy/iscroll/commit/d275166c64f24e41c7c701cd4d41fed4f7f11fbf

Thanks.

**Comment by sculove** [comment]
iscroll has a bug about pointer event binding.
if you use pointer event, you face a problem.
iScroll isn't actively maintained. so, I forked iscroll 5.1.3
https://github.com/naver/egscroll

you can download from bower
```js
bower install egscroll#master
```

I hope that iscroll project will be activated.  
but, I have no choice, now
