### ISSUE TITLE
Tap: true firing multiple events, iscroll-5.1.3

### ISSUE THREAD

**Issue by suniltmc** [cubiq/iscroll#1010]
I have an issue with the click event for the scroller.

I have a header list, when the iscroll options for click and tap are set to true, there are multiple events are firing and when I change them to false, it is working good in desktop and IOS but not in android, in android it is not even getting clicked, I tried to use the custom tap event as well like, tap: "myTap" and listened to that event, then it again firing multiple times. 

Please let me know if there is any workaround for this or I have to change the version.

**Comment by sculove** [comment]
check this comment.
https://github.com/cubiq/iscroll/issues/361#issuecomment-194189473

**Comment by sculove** [comment]
I forked iscroll 5.1.3
https://github.com/naver/egscroll

egscroll fix this issue.
you can download from bower
```
bower install egscroll#master
```

**Comment by sculove** [comment]
I merged
