### ISSUE TITLE
scroll over FB comments block

### ISSUE THREAD

**Issue by drumpf** [cubiq/iscroll#1014]
Hi,
Iscroll seems not to be working over Facebook comments block.
Scrolling is fine before and after the block, but trying to scroll over the comments block itself (click and drag anywhere inside a comments block on any page that has iscroll embedded) doesn't seem to work.
Any insights?

**Comment by dt1973** [comment]
So it works after all or why'd you close?

**Comment by drumpf** [comment]
It doesn't. Found out cubiq related to that in another thread regarding iframes in general.
The workaround is to create a dummy top layer over the iframe that allows scrolling, and then catch clicks and send them to the iframe to trigger events.
Described here: http://stackoverflow.com/questions/15248970/iframe-prevents-iscroll-scrolling-on-mobile-safari

**Comment by dt1973** [comment]
Cool, Timo's old thread. Yeah, I was just curious because generally it's bad practice closing issues without an explanation, so thanks!
