### ISSUE TITLE
directionY method doesn't work when i scroll with mouse 

### ISSUE THREAD

**Issue by alex1012** [cubiq/iscroll#1018]
this method work correct when you scroll with mouse swipe, or you scroll with touch devices, but when i use scroll wheel he is return 0 or last value which was set when he worked correct

Can somebody help me on this trouble?

**Comment by jonathanheilmann** [comment]
It's a known bug, but has bot been resolved yet. For solution see https://github.com/cubiq/iscroll/issues/652

**Comment by sculove** [comment]
check this issue #652. I merged. thank you
