### ISSUE TITLE
es6 module support?

### ISSUE THREAD

**Issue by davidmaxwaterman** [cubiq/iscroll#1025]
I wonder if iscroll supports es6 modules and, if so, if you could give me an example of how to use it as an es6 module. I'm using babel to preprocess my own js files, and would like to try to use rollup to help me only distribute needed files.

**Comment by glebmachine** [comment]
No, there is no support of native es6 module.

But, but iscroll use UMD syntax, that supports by most common builders like webpack.

**Comment by glebmachine** [comment]
Closed due inactivity

**Comment by Anikinly** [comment]
it's seems better
