### ISSUE TITLE
IScroll not defined when loading with RequireJS ??

### ISSUE THREAD

**Issue by btburton42** [cubiq/iscroll#1027]
We're using iScroll for a particular component on our site and with the latest release we're seeing `IScroll is not defined(…)` when trying to call `new IScroll xxx` in our AMD component.

I see that you recently added AMD support. Have you noticed any regressions?

Passing it in as a named variable in the define block has no effect.

**Comment by btburton42** [comment]
nvm. once the header was configured correctly we were good to go.

**Comment by alvarotrigo** [comment]
@btburton42 how did you solve it??
What header are you talking about?

**Comment by btburton42** [comment]
our UMD header. it was not passing iScroll in as an AMD defined variable, but instead defaulting to the window object. so once iScroll gained AMD support this was failing. just had to name some variables correctly.

**Comment by corsachriz** [comment]
Still doesn´t work for me in the latest Version fullpage  2.9.6 and scrolloverflow  0.0.5.

My config.js:

`
requirejs.config({
	baseUrl: 'js',
	paths: {
		jquery: 'jquery-3.3.1.min',
		IScroll: 'scrolloverflow',
		fullpage: 'jquery.fullPage'
	},
	 shim: {
         IScroll: {
               deps: ['jquery']
         },
         fullpage: {
               deps: ['IScroll']
         }
    }
});
`
and

`define(['jquery', 'IScroll', 'fullpage'], function($,IScroll) {
		$('#fullpage').fullpage();	
});`

causes

`IScroll is not defined in scrolloverflow.js:2393 `
