### ISSUE TITLE
Always visibile scroll bar for Mac Os X 

### ISSUE THREAD

**Issue by alvarotrigo** [cubiq/iscroll#1031]
Does iScroll.js support an always visible scrollbar for Mac OS X?  I don't seem to make it work: https://jsfiddle.net/511wmq3h/

**Comment by sculove** [comment]
@alvarotrigo I don't understand what you said.
I fix your demo.
https://jsfiddle.net/fcyp07sn/15/

Is this right?

**Comment by alvarotrigo** [comment]
Nop. I don't know how can I say it clearer. 
I just want the scroll bar created by iScroll to be always visible, not only when I scroll up or down. 

In Mac Os X the scroll bar disappears when the user stops scrolling.

**Comment by cubiq** [comment]
```
scrollbars: true,
fadeScrollbars: false,
hideScrollbars: false
```

seems to be working

**Comment by alvarotrigo** [comment]
@cubiq the scroll bar disappears after the user stops scrolling. You can easily test it on the jsfiddle I provided. 

![nobar](https://cloud.githubusercontent.com/assets/1706326/14739177/c428402e-087d-11e6-879b-7941a3714ae3.JPG)

As you can see on the picture there's no scroll bar at all.

**Comment by cubiq** [comment]
double check spelling. all you need is `fadeScrollbars:false` (plural)

**Comment by alvarotrigo** [comment]
@cubiq I'm getting the same result. No initial scroll bar and it disappears whenever I stop.
[Reproduction online](https://jsfiddle.net/511wmq3h/2/)

Here's a video. It is quite laggy as I was using a connection to a remote computer, but you can see what I'm not crazy when say the scroll bar disappears
![untitled screencast 1](https://cloud.githubusercontent.com/assets/1706326/14740279/a91d9e84-0885-11e6-8066-4ed28523d56a.gif)
:

**Comment by cubiq** [comment]
please check @sculove 's example and simply set fadeScrollbars to false.

**Comment by alvarotrigo** [comment]
@cubiq I did? Why I got no comments on my video proof? 

Few things regarding his fiddle: 

- His example doesn't scroll with mouse wheel
- His example still not showing any scroll bar on page load
- His example hides the scroll bar after scrolling

And just for you to believe me, here's the new video with his own fiddle: 
![notworking2](https://cloud.githubusercontent.com/assets/1706326/14741124/09fa89a0-088c-11e6-9558-6d4afe7bbc30.gif)

**Comment by cubiq** [comment]
you have to set the fadescrollbars to false (in your video is "true")

**Comment by alvarotrigo** [comment]
Thanks, but that was not the problem.

It was not about the options, but about the HTML markup , that seems to require the wrapper element `scroller` and the CSS property `overflow:hidden` that I was missing. 

https://jsfiddle.net/511wmq3h/8/

**Comment by cubiq** [comment]
that's why I was suggesting to check @sculove example :)

glad we came to the bottom of it
