### ISSUE TITLE
input make scroll position error

### ISSUE THREAD

**Issue by uniquezhuo** [cubiq/iscroll#1037]
i create a height auto change textarea in IScroll.  when i input a lot of things. the i can not scroll to the top of the page . And the bottom of the page has a large blank. it seems the elements in iscroll move topper.

**Comment by glebmachine** [comment]
Can you provide repro, please?

**Comment by HappySusan** [comment]
i have the same problem

**Comment by HappySusan** [comment]
here is the question:
everything is normal, however, after i input someting and close the mobile keyboard, i cannot go to the top of the current page. If there is any conflict between input tag and iscroll.

**Comment by dongkaipo** [comment]
@uniquezhuo is there any way to solve it?

**Comment by MinuteWong** [comment]
i have same problem,when i close the mobile keyboard i cannot go to the top. there are some white space in the bottom.

**Comment by MinuteWang** [comment]
maybe just miss overflow;hidden.
like this[
<div style="position:relative;overflow:hidden">
     <div class="scroller"></div>
</div>
](url)

**Comment by MinuteWang** [comment]
maybe just miss overflow:hidden;
like this
`<div style="position:relative;overflow:hidden;height:100%">
    <div class="scroller"></div>
</div>`

**Comment by MinuteWang** [comment]
`maybe just miss overflow:hidden;
like this`

**Comment by MinuteWong** [comment]
maybe just miss overflow:hidden;
like this:`<div style="position:relative;overflow:hidden;height:100%"><div class="scroller"></div></div>`
