### ISSUE TITLE
problem with $.Deferred() and done()

### ISSUE THREAD

**Issue by meisam3322** [cubiq/iscroll#1045]
i need to load some html from server i use $.Deferred and ajax to get it and use this code to show contents : 

`                api.about().done(function (list) {
                    $('#about #aboutContent #scroller').find('li').html(list);
                    scrollAbout = new IScroll('#about #aboutContent #wrapper', {
                        mouseWheel: true,
                        scrollbars: true,
                        fadeScrollbars: true
                    });
                });`

but iscroll not works. and when i resize window iscroll starts to work. i think there is problem to calculate height or something. is there any idea to help ??

**Comment by glebmachine** [comment]
Make sure all images has `height` attr, or loaded when you initiate iscroll.

**Comment by meisam3322** [comment]
thanks . i set height for all images. but not work yet.

**Comment by meisam3322** [comment]
i check all images loaded before create or refresh iscroll and it works 

`
                   $('#about #aboutContent #scroller').find('img').load(function () {
                        scrollAbout = new IScroll('#about #aboutContent #wrapper', {
                            mouseWheel: true,
                            scrollbars: true,
                            fadeScrollbars: true,
                        });
                        setTimeout(function () {
                            scrollAbout.refresh();
                        }, 100);
                    });
`

but technically this is not good solution i think

**Comment by glebmachine** [comment]
Yep.
Better do like this:
```js
var myScroll = IScroll('#about #aboutContent #wrapper', { ...opts })
$(''#about #aboutContent #wrapper img').load(function(){
  myScroll.refresh();
});
```

This code will refresh iScroll each time when new image become loaded

**Comment by meisam3322** [comment]
it works. very nice solution . thanks for your help...

**Comment by glebmachine** [comment]
You are welcome)
