### ISSUE TITLE
iscroll and flex container

### ISSUE THREAD

**Issue by oufresh** [cubiq/iscroll#1046]
Hello,

can iscroll work with flexible containers? Suppose to have this scenario 
- "div" external flex container (position absolute) with different elements
- "div" that can grow to a maximum height or has a fixed height (flex)
- "ul" inside the "div" with a dynamic numbers of "li" elements
- arbitray "div" element (flex)

When the number of "li"s grows the div should scroll and it does with iscroll but the scrollbar is not drawn correctly but on the entire side of the external container.
As soon as I can I'll create an example on fiddle.

Thanks a lot

**Comment by glebmachine** [comment]
Waiting for your example on fiddle)

**Comment by oufresh** [comment]
I found a solution to that problem using in the flexible wrapper these two css property:

"position: relative;"
"max-height: YYpx"

**Comment by glebmachine** [comment]
Nice)
