### ISSUE TITLE
On initialized function

### ISSUE THREAD

**Issue by codeplaygoa** [cubiq/iscroll#1062]
i want to fire a function once iscroll is initialized.

**Comment by glebmachine** [comment]
It's ok, what's the question is?

**Comment by codeplaygoa** [comment]
when iscroll is initialized i want to fire my custom function. i have seen there are iscroll events like "beforeScrollStart","scrollEnd" etc.. 
but i couldnt find an event which tells me iscroll is initialized

**Comment by glebmachine** [comment]
iScroll initialised right after `new iScroll()` call.
Just put your code right after this block of code.

**Comment by codeplaygoa** [comment]
ok thanks
