### ISSUE TITLE
iscroll-probe.js scroll event isn't working but scrollEnd or scrollStart

### ISSUE THREAD

**Issue by myAoyue** [cubiq/iscroll#1106]
I import iscroll-probe.min.js with CDN(https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll-probe.min.js) and do following:

`
                myScroll.on('scroll', function() {
                    alert('scroll');
                });
`

the event not triggered ..

**Comment by AndreasKr** [comment]
have you set the probe type (e.g. probeType: 3) - see iscroll docs?

Regards
Andreas

**Comment by myAoyue** [comment]
Oh... I missed
