### ISSUE TITLE
iscroll not working in Android latest version 6.0.1 and chrome beta

### ISSUE THREAD

**Issue by kishorsathe** [cubiq/iscroll#1118]
Hi Team, 

We have used latest version of iscroll, we are facing issue in latest Android and chrome beta browser, 
scroll is not working normal, its very slow and hard to drag.

Issue also reproducible in your below Demo in mobile browser chrome beta and latest android version (6.0.1).

http://lab.cubiq.org/iscroll5/demos/simple/

**Comment by Pauxis** [comment]
I have the same issue on 6.0.1 and looking for a solution

**Comment by moumoutang** [comment]
This is the same question in 5.2.0;You can try to set options like this

disablePointer: true, // important to disable the pointer events that causes the issues
disableTouch: false, // false if you want the slider to be usable with touch devices
disableMouse: false // false if you want the slider to be usable with a mouse (desktop)

 disable pointer event，force to use touch

**Comment by lorddarkzic** [comment]
related to https://github.com/cubiq/iscroll/issues/1109

**Comment by sculove** [comment]
Some Android 6.0.1 does not support `pinch-zoom` value.
ex) Samsung Galaxy Note5, Samsung Galaxy S6, ...

**Comment by aaronguostudio** [comment]
I solved the issue with moumoutang's solution.
