### ISSUE TITLE
`cosole.error` for passive event listener in Chrome54+

### ISSUE THREAD

**Issue by sculove** [cubiq/iscroll#1119]
I test iScroll demo file in Chrome55.
I'm face a error message.

![2016-12-29 10 37 55](https://cloud.githubusercontent.com/assets/1383952/21535021/ef933c00-cdb2-11e6-8dd6-4aa870a1859c.png)

There is an error in this code.
```js
document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
```

### cause
If an event listener is added to the document, body, or window and is a scroll blocking (touchstart, touchmove) listener it will be have `passive options` to be `true` 
and we will face a following error 

- chrome platform status: https://www.chromestatus.com/features/5093566007214080
- EventListenerOptions : https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by RByers** [comment]
As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway.
