### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive. See

### ISSUE THREAD

**Issue by 1003865572** [cubiq/iscroll#1130]
Iscroll  Cannot use normally

My Chrome warning

Unable to preventDefault inside passive event listener due to target being treated as passive. See

**Comment by 1003865572** [comment]
![My Chrome console warning](https://cloud.githubusercontent.com/assets/7412054/22810699/511d0d64-ef75-11e6-8d09-65d45ab13eb4.png)

**Comment by mofelee** [comment]
add “passive: false ” will solve this problem
```js
document.addEventListener('touchmove', this._preventDefault, { passive: false });
````

**Comment by ruanxiaoquan** [comment]
thank you

**Comment by 1003865572** [comment]
@MofeLee  my Chrome Latest version 56.0.2924.87  。This is the latest version  I can't update IScroll code 。How to do it?

**Comment by 1003865572** [comment]
@ruanxiaoquan  哥们儿  你是不是  拉到最新版本的 IScroll 然后改源码了，

**Comment by dsvanidze** [comment]
@MofeLee thanks, works perfect, but how is support for other browsers? Can User become some error if have no Support for Passive Event Listeners?

**Comment by Loque-** [comment]
You could do this to cover older browsers also;

```
function supportsPassive(){
    var supportsPassiveOption = false;
    try {
        var opts = Object.defineProperty({}, 'passive', {
            get: function() {
                supportsPassiveOption = true;
            }
        });
        window.addEventListener('test', null, opts);
    } catch (e) {
        // 
    }
    return supportsPassiveOption;
}
```

Then in your event listeners;

```
document.addEventListener('touchmove', this._preventDefault, supportsPassive ? { passive: true } : false);
```

**Comment by mrdulin** [comment]
@svanskivar https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection

**Comment by kcray** [comment]
What lines need to be adjusted in the iScroll code itself? Can anyone supply that?

**Comment by sculove** [comment]
I applied all examples like this.
https://github.com/cubiq/iscroll/blob/master/demos/2d-scroll/index.html#L19-L22

**Comment by cbravo** [comment]
@sculove this still seems to be happening to me using iscroll probe set on probeType: 3. I have followed the above.. would something else be wrong?

**Comment by ufologist** [comment]
3 way to fix IScroll can not scroll smoothly in new chrome version(56+?)

* Add `touch-action` style to the wrapper of the scrolling area

   ```css
   #wrapper {
       touch-action: none;
   }
   ```

   [Unable to preventDefault inside passive event listener](https://stackoverflow.com/questions/42101723/unable-to-preventdefault-inside-passive-event-listener)
   > See this [blog post](https://developers.google.com/web/updates/2017/01/scrolling-intervention). If you're call `preventDefault` on every `touchstart` then you should also have a CSS rule to disable touch scrolling like `.sortable-handler { touch-action: none; }`

* `disablePointer` to disable listen pointer event

  ```javascript
  // IScroll listen pointer event which case it can not scroll smoothly
  new IScroll('#wrapper', {
        disablePointer: true
  });
  ```

* document touchmove use passive false to preventDefault

  ```javascript
  document.addEventListener('touchmove', function (event) {
      event.preventDefault();
  }, {
      passive: false
  });
  ```

  [移动Web滚动性能优化: Passive event listeners](https://segmentfault.com/a/1190000007913386)
  > 如果我们在 touchstart 事件调用 preventDefault 会怎样呢？这时页面不会滚动或缩放。那么问题来了：**浏览器无法预先知道一个监听器会不会调用 preventDefault()，它需要等监听器执行完后，再去执行默认行为，而监听器执行是要耗时的，这样就会导致页面卡顿。**
  >
  > 当你触摸滑动页面时，页面应该跟随手指一起滚动。而此时你绑定了一个 touchstart 事件，你的事件大概执行 200 毫秒。这时浏览器就犯迷糊了：如果你在事件绑定函数中调用了 preventDefault，那么页面就不应该滚动，如果你没有调用 preventDefault，页面就需要滚动。但是你到底调用了还是没有调用，浏览器不知道。只能先执行你的函数，等 200 毫秒后，绑定事件执行完了，浏览器才知道，“哦，原来你没有阻止默认行为，好的，我马上滚”。此时，页面开始滚。
  >
  > 如果 Web 开发者能够提前告诉浏览器：“我不调用 preventDefault 函数来阻止事件事件行为”，那么浏览器就能快速生成事件，从而提升页面性能。
  >
  > `passive` 就是为此而生的。在 [WICG](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) 的 demo 中提到，即使滚动事件里面写一个死循环，浏览器也能够正常处理页面的滑动
  >
  > **我们可以通过传递 passive 为 true 来明确告诉浏览器，事件处理程序不会调用 `preventDefault` 来阻止默认滑动行为。**
