### ISSUE TITLE
iscroll scroll hardly with chrome dev mode in version ^5.1.3

### ISSUE THREAD

**Issue by gitby15** [cubiq/iscroll#1147]
Iscroll has some problem in chrome mobile dev mode, It scroll hardly.
It is good in chrome of pc, but bad in chrome of mobile phone, also bad in chrome with device dev mode. is something wrong with touchmove?
maybe something wrong.
in version before 5.1.3 is good, 5.1.3 bad, 5.2.0 bad, thank you very much:D

**Comment by kaansoral** [comment]
I've notice a hard scrolling issue too, did you solve it?

**Comment by chang0022** [comment]
look at the demo. https://github.com/cubiq/iscroll/blob/master/demos/simple/index.html 
use this script https://github.com/cubiq/iscroll/blob/master/demos/demoUtils.js then chrome mobile dev moda is OK. 
![image](https://cloud.githubusercontent.com/assets/6067222/25979341/716086c4-36fa-11e7-8be2-4624603e87b6.png)

**Comment by gtdalp** [comment]
@chang0022  Thank you very much,Demo can be used！
