### ISSUE TITLE
scrollToElement not setting current position

### ISSUE THREAD

**Issue by sambengtson** [cubiq/iscroll#1151]
Usage is:

`scroll.scrollToElement(scrollElement, 600, 0, -50, IScroll.utils.ease.circular);`

If calling next() or prev() shortly after, it seems that it scrolls all the way back to the top and focuses on the second element.  Am I missing something here?  I've tried a couple of things without much luck.

**Comment by jonkrusell** [comment]
scrollToElement never sets the currentPage

Here's my fork with a fix:

https://github.com/jonkrusell/iscroll/commit/34bfcff1a0e596e89aa2d0fbfb7a563ced4ce2a2

**Comment by sambengtson** [comment]
@jonkrusell Thanks.  Glad somebody is paying attention on here.
