### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

### ISSUE THREAD

**Issue by huoxudong125** [cubiq/iscroll#1154]
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

_move @ VM46763 iscroll-probe.js:528
handleEvent @ VM46763 iscroll-probe.js:1689

**Comment by huoxudong125** [comment]
this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention). You probably need to add an appropriate `touch-action` [CSS rule ](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)to explicitly disable touch scrolling.

**Comment by cbravo** [comment]
+1
