### ISSUE TITLE
New chrome bug

### ISSUE THREAD

**Issue by gtdalp** [cubiq/iscroll#1155]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by teekcode** [comment]
same on http://lab.cubiq.org/iscroll5/demos/barebone/ when open in 58.0.3029.110 (64-bit) chrome when open in its device toolbar

**Comment by gtdalp** [comment]
Yes,The new version of Google Chrome will have this error.

**Comment by notdotscott** [comment]
Same as this bug? 
https://github.com/cubiq/iscroll/issues/1130

**Comment by notdotscott** [comment]
Also: 
https://github.com/cubiq/iscroll/issues/1147

**Comment by gtdalp** [comment]
@d-scott Thank you~！
