### ISSUE TITLE
It can't work in chrome mobile

### ISSUE THREAD

**Issue by zsqosos** [cubiq/iscroll#1157]
- I use the iScroll in a webApp.it scroll smoothly in foxfire and chrome for desktop，but it can't work in chrome mobile(android),Then I found `PointerEvent` that in new chrome cause iScroll can't work.
- It worked when i add `<script>window.PointerEvent = void 0</script>` in the head tags
- But it prompt `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.See https://www.chromestatus.com/features/5093566007214080` when scroll

**Comment by coderitual** [comment]
Did you try to build library from sources? I can't reproduce this on my fork.

**Comment by zsqosos** [comment]
I solved it，add the `touch-action:none` with the element that will scroll, it can work

**Comment by lmw6412036** [comment]
@zsqosos thinks

**Comment by Reggino** [comment]
@zsqosos thanks. This should be part of the library.
