### ISSUE TITLE
iScroll is shower on large data.

### ISSUE THREAD

**Issue by swaranan** [cubiq/iscroll#1178]
Hi, i have  a problem with iscroll when i have large data iscroll can't scroll smoothly. But on small data it working fine.Please help..

Small data: [Small data link](http://173.255.203.57/Xeraya/)
Large data: [Large data link](http://173.255.203.57/Xeraya/loader/)

**Comment by lensh** [comment]
you can use JRoll, it also scroll smoothly when it has large data.
https://github.com/chjtx/JRoll

**Comment by swaranan** [comment]
Thanks for your reply. I have gone very far my project with iScroll so i can't switch from iscroll now. Will look after  JRoll on other project.
