### ISSUE TITLE
iScroll referesh not working if i change route.

### ISSUE THREAD

**Issue by swaranan** [cubiq/iscroll#1189]
Hi, i am using iscroll on my project its working well on desktop. But on mobile If i rotate my phone the iscroll not working and it happens when i rotate my phone from a inner page and going to home page.If i rotate my phone from home page its working well.But if i rotate my phone on any inner page and goes home page iscroll stop working.
Please help..

Code i am using: 

```
var myScroll;

	myScroll = new IScroll('#wrapper', {
		scrollX: true,
		scrollY: true,
		startX: -2600,
		startY: -2600,
		freeScroll: true,
		probeType: 1,
		mouseWheel: true,
		click: true,
		tap: true,
		bounce: false,
		fadeScrollbars: false,
		disablePointer: true,
		disableTouch: false,
		disableMouse: false,
		mouseWheelSpeed: 500,
		resizePolling: 150
	});
```
and i am calling this on document ready.

Link: [Link](http://173.255.203.57/Xeraya/loader/)

**Comment by jiachaosun** [comment]
did you try the refresh() method?

**Comment by swaranan** [comment]
Yes i did..I have added:
`myScroll.refresh();`
but not working.

**Comment by swaranan** [comment]
Solved it... great plugin...
