### ISSUE TITLE
Website iscrolljs.com down

### ISSUE THREAD

**Issue by mgrubinger** [cubiq/iscroll#1248]
It seems that http://iscrolljs.com/ is down for a while now (at least 2 weeks). 

Let me know if I can be of any help getting the site up again.

**Comment by dt1973** [comment]
I thought this project has been dead for years. Is it really needed anymore though with the likes of Framework7?

**Comment by mgrubinger** [comment]
you're probably right, also because all the documentation is available here on github. Closing this issue.

Looking at the issues though, it seems there are still quite a few people using it when supporting legacy devices.
