### ISSUE TITLE
onScroll event not fired.

### ISSUE THREAD

**Issue by Syler921** [cubiq/iscroll#1255]
iScroll version : 5.2.0 

I'm trying to attach onScroll event with event name "scroll" and "scrollMove" but it doesn't fire scroll event.

```
this.iscrollRefference.on('scrollMove', function () {
      console.log('move');
});

this.iscrollRefference.on ('scroll', function () {
      console.log('move');
});
```

**Comment by chrisxxp** [comment]
i think you should use the iscroll-probe.js but iscroll.js
