### ISSUE TITLE
How do I scroll to the end?

### ISSUE THREAD

**Issue by matthew-dean** [cubiq/iscroll#179]
This seems like it should be simple, but how do I scroll to the end (bottom or right of an element with a scroll? I notice if I set scrollTo to a large number, it just makes the scroller bigger. And scrollToElement is not what I want, because I want to scroll past any elements to just the maximum scroll number.

**Comment by kozuch** [comment]
The maxScrollY value works for version 5 too even though it is not documented.

**Comment by shuizhongyueming** [comment]
this is really useful for me, thanks

**Comment by LeandroFranciscato** [comment]
Thanks, this help a lot
