### ISSUE TITLE
Snap on one element then scroll normally

### ISSUE THREAD

**Issue by bc-vnbc** [cubiq/iscroll#189]
Hi,

I have an issue with this excellent iScroll plugin!

I'm building an interactive magazine for ipad, and would like to have only the first div page snapped and then scroll normally after…

exemple :

div one page (height:576px)
div large normal scroll (height > 576px)

So it snaps the first div, and after, the scroll is done without snap.

Can you help me ?

Thanks!
B.

**Comment by eliteproxy7** [comment]
i am using iScroll5 how can this be achieved? I have 2 divs with the same class name and using that as the snap target  the first div is 200px and the second one is 800  but it doenst let me scroll normal after the first snap
