### ISSUE TITLE
Please consider using scrollHeight rather than offsetHeight

### ISSUE THREAD

**Issue by ghost** [cubiq/iscroll#213]
Nice work! Thanke you! Please consider this:

//that.scrollerW = that.scroller.offsetWidth;
//that.scrollerH = that.scroller.offsetHeight;
that.scrollerW = that.wrapper.scrollWidth;
that.scrollerH = that.wrapper.scrollHeight;

It will allow:
# wrapper { padding: Npx }

**Comment by ganmor** [comment]
I think using scrollHeight / scrollWidth would be a good idea too.
```
this.scrollerWidth = Math.round(this.scroller.scrollWidth * this.scale); 	
this.scrollerHeight = Math.round(this.scroller.offsetHeight * this.scale);
```
If the overflow on the body is set to hidden, the max height and width of the scroller will be the page height / width.
