### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null 

### ISSUE THREAD

**Issue by Jakobud** [cubiq/iscroll#266]
When trying to load v4.2.2 in the latest Chrome, I get:

`Uncaught TypeError: Cannot read property 'style' of null`

referring to line: 90: 

`that.wrapper.style.overflow = 'hidden';`

Only other thing I have loaded is jQuery.

**Comment by peterdoescode** [comment]
Still got the issue on iscroll 5: http://urb.li/Yf3j/2A2BiLaq

**Comment by Rutulpatel7077** [comment]
TypeError: Cannot read property 'style' of undefined
