### ISSUE TITLE
iScroll stuck when finger leaves display outside of the application

### ISSUE THREAD

**Issue by Prinzhorn** [cubiq/iscroll#297]
I'm on a Galaxy S2 with Android 4.0.2. The browser is the normal Android browser. Firefox, Chrome and Opera are fine. The bug can be reproduced with the iScroll simple demo.

When I reach the bottom of the list but try to scroll further, the list moves up due to bounce enabled. But if I move my finger far enough to the top and leave it outside of the app on the black top bar, the list gets stuck. I can even use my finger again to push to list completely off screen.

Maybe the `touchleave` event could solve this, it's supported by Android and iOS. I think it should be bound to the document and not the the scroll area.

**Comment by zcoding** [comment]
This is still an issue, still, still, still...

**Comment by zhump** [comment]
This is still an issue ？？？！！
