### ISSUE TITLE
Scroller margin is ignored

### ISSUE THREAD

**Issue by mattpepin** [cubiq/iscroll#32]
If the scroller element has a margin, it is ignored and you cannot scroll to the bottom. I fixed the problem by adding the following code in refresh() and _checkSize().

add:
var marginY = that.scroller.offsetParent.scrollHeight - that.scroller.offsetHeight;

edit:
that.scrollerH = m.round((that.scroller.offsetHeight + marginY - that.offsetBottom - that.offsetTop) \* that.scale);

PS.: Sorry I don't know github enough to create a patch but it's an easy fix.

**Comment by vanuatu** [comment]
I got the same error
