### ISSUE TITLE
Mouse Wheel Support?

### ISSUE THREAD

**Issue by daslicht** [cubiq/iscroll#397]
On you homepage you write : 

It now supports not only touch events but also pointers, key presses, remote controls and of course the good old mouse.

How do I enable the Mouse Wheel Support?

**Comment by Sjael** [comment]
[https://github.com/cferdinandi/smooth-scroll](https://github.com/cferdinandi/smooth-scroll )

Would there be anything to learn from this as to implement a smooth mouse wheel scroll @cubiq ?

**Comment by Sjael** [comment]
I don't believe this is fixed, so why is this issue closed?
