### ISSUE TITLE
iframe within scrollable content

### ISSUE THREAD

**Issue by doublejosh** [cubiq/iscroll#41]
Curious if there is a workaround known for dealing with iframes within scrollable content?

Everything works fine on page, but when touching the iframe normal scroll behavior takes over including moving the viewport and off-document scrolling with the gray background.

**Comment by manico** [comment]
So, this cannot be fixed?
iScroll cannot be used if there is iframe inside scrollable container?

**Comment by chinochano** [comment]
I couldn't get @heldrida's fix to work so I tried my own approach with the iScroll events.

It's only a partial fix, but works well enough for me. It allows you to start scrolling with the pointer outside of an iframe and continue to scroll over an iframe (already something!). However, if you stop on top of the iframe, pointer-events are set back to "auto", which means you can now click on the iframe links/buttons but not scroll the container page any more. As I said it's a partial fix, but it's clean and straight-forward. Thought it might be useful to some.

```
iScroll.on('scrollStart', function() {
	$('iframe').css("pointer-events", "none");
});
iScroll.on('scrollEnd', function() {
	$('iframe').css("pointer-events", "auto");
});
```

**Comment by kchabra093** [comment]
@daizumi  what happened when user stop mouse on iframe and click on iframe for play video?

**Comment by chinochano** [comment]
@kchabra093 If you stop scrolling on top of an iframe and click it, the video player (or whatever iframed content) will respond to the click normally. It's only between scrollStart and scrollEnd that pointer events (scrolling, clicking, etc) are ignored.
