### ISSUE TITLE
Allow to remove event

### ISSUE THREAD

**Issue by setthase** [cubiq/iscroll#438]
Have you consider adding `off` (detaching events) method to iScroll5? It could be looks something like this:

``` javascript
  off: function (type, fn) {
    if ( !this._events[type] ) {
      return;
    }

    var index = this._events[type].indexOf(fn);

    if (index > -1) {
      this._events[type].splice(index, 1);
    }
  }
```

I could make pull request with this, but currently I'm to lazy to fight with build system and Contributor License Agreements ;)

**Comment by nltesown** [comment]
It doesn't look like `probeType` option can be updated once the IScroll instance has been created. If I use `off` to stop listening to scroll events, I'd like to be able to switch to a less resource-intensive `probeType` (from 3 to 1) as well. What do you think?
