### ISSUE TITLE
scrollend on touch block

### ISSUE THREAD

**Issue by francescoagati** [cubiq/iscroll#447]
Hi,
scrollEnd should be triggered also when the user block the scroll tap on the scroll while is in movement in v5

**Comment by karneaud** [comment]
scrollEnd not working on Android 4.0.3 Chrome

**Comment by thin-k-design** [comment]
When at the beginning or end of the scrolling wrapper, if I scroll against the border (no elements moving), the scrollStart is firing, but there is no ScrollEnd firing. Happens only with snap on.
