### ISSUE TITLE
iscroll CANCEL_EV handler breaks media playback on iOS

### ISSUE THREAD

**Issue by foresto** [cubiq/iscroll#52]
iScroll intercepts click events and replaces them with with fake click events so that wrapped elements can still handle them.  Unfortunately, it fires its fake click event via setTimeout(), which causes event handlers to run outside the scope of a user action, thus preventing media playback and download functionality on iOS >= 4.2.  This breaks the tap-to-play functionality of my application's scrolling pane of video buttons.

The problem exists in iScroll Beta 4 / git 0398d2a, but not iScroll Lite and not iScroll 3.  The offending code lies within iScroll's `_end()` function.

In order to fix it, iScroll must allow wrapped controls to receive their user input events (even fake ones) while the original event handler is still running.  That means not calling dispatchEvent() from within a setTimeout() callback.

For reference, see the **User Control of Downloads Over Cellular Networks** section of [Apple's documentation](http://developer.apple.com/library/safari/#documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html).  There is a fair bit of related discussion around the net, for example: [here](http://stackoverflow.com/questions/3009888/autoplay-audio-files-on-an-ipad-with-html5/4259825#4259825).

**Comment by akhoury** [comment]
@cubiq has this issue been handled in v5 ? and if so, what are the opt-in/out options?

Thanks
