### ISSUE TITLE
click event fired twice times on iScroll v5

### ISSUE THREAD

**Issue by kimleng** [cubiq/iscroll#547]
hello, I have a problem with click event on iScroll 5. Some elements, they fired only one time. But some elements, they fired twice times. Even I changed to tap, it is also same issue. How should I do?

**Comment by valnub** [comment]
Seeing the same problem in 5.1.1. Is this fixed in the newest 5.1.3?

**Comment by salcott** [comment]
Still has the problem with v5.1.3 ....

**Comment by sculove** [comment]
@salcott how about using iScroll v5.2.0 ?

**Comment by wv1124** [comment]
iScroll v5.2.0 ~ (c) 2008-2016 Matteo Spinelli ~ http://cubiq.org/license
mac chrome 52.0.2743.82 (64-bit)
 
iscroll-probe.js:264 Uncaught TypeError: Cannot assign to read only property 'view' of object '#<MouseEvent>'me.click 
@ iscroll-probe.js:264_end 
@ iscroll-probe.js:629handleEvent @ iscroll-probe.js:1650
