### ISSUE TITLE
Problems with width and height on scrolling area

### ISSUE THREAD

**Issue by ralphtheninja** [cubiq/iscroll#551]
Hi,

I've tested some of the demos and they all work well when it comes to the scroller having a limited scrolling area. However, I'm adding elements to the DOM dynamically and want to create scrollers on the fly. When I do this the scroller is created and the scrolling functionality works as it should apart from one thing, the scrolling area is "infinite", meaning there is no natural end to the scroller, if you know what I mean.

Any ideas how to troubleshoot this?

Thanks

**Comment by LeandroFranciscato** [comment]
This help me, thank you!
