### ISSUE TITLE
When dragging with the mouse to scroll either downward or upward causes white flash/flicker in Google Chrome.

### ISSUE THREAD

**Issue by hugomoss** [cubiq/iscroll#569]
Hello,

I have found that when enabling iScroll, and then flicking upward or downward with my mouse pointer, causing scrolling, creates a white horizontal bar that flashes while scroll ing downward or upward. When scrolling upward, the flash bar is on the top, and vice-versa.  Mousewheeling while using iscroll causes no issues, probably because it goes much slower than the animation, in one flick it scrolls all the way to the top or bottom, which is good.  But the white flash is not looking good. 

I've tried adding -webkit-backface-visibility:hidden, and -webkit-transform: translateZ(0), and -webkit-perspective: 1000 to almost every container and element on my webpage.  Yet the flicker persists.

Please if anyone can help me on this issue, I would really like to use this plugin, it is a great plugin.  Thanks.

**Comment by lostomato** [comment]
wrapper and scroll should be both at the same "absolute" position
