### ISSUE TITLE
Zoom Issues when setting zoomMin below 0.5

### ISSUE THREAD

**Issue by springlab** [cubiq/iscroll#586]
I'm using iScroll 5 for a project that require scrolling through a history timeline. The timeline's image is large. Around 7000x3000. To see the whole timeline, I need to set the zoomMin and zoomStart to 0.3. However... anytime I set those values below 0.5 it starts to glitch really bad when zooming in or out. It makes the entire app flash and go blank. But as soon as I set zoomMin and zoomStart to 0.5 and above.. it starts working fine again. Any help you could provide on this would be GREATLY appreciated.

**Comment by kadosh1000** [comment]
@springlab @cubiq 
I also experiencing the same problem.
Would love to know how you managed to fix it or workaround it.
