### ISSUE TITLE
 iScroll V.5 TypeError: 'undefined' is not an object (evaluating 'this.scroller.style')

### ISSUE THREAD

**Issue by nelsonic** [cubiq/iscroll#601]
using iScroll v.5.1.1 and getting this issue when running rake tests.
TypeError: 'undefined' is not an object (evaluating 'this.scroller.style')

We are running jQuery v1.10.2 
additional info: we are using Capybara::Poltergeist (PhanotomJS) to run the headless browser tests.
When I try the page in browser I do not see any errors. :-(

also:
phantomjs[19856:507] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

Related to: https://github.com/cubiq/iscroll/issues/134
*Still an issue* in **V.5**

**Comment by nelsonic** [comment]
Closing as no longer working on the project where we saw this issue.

**Comment by tatjana19** [comment]
Hi there, i have the same error on ipad. Is there a solution for this issue?

**Comment by astrapi69** [comment]
I had the same error message. This happen because i did not set the appropriate element with iScroll. The element was a 'tbody'-tag. I moved it to the 'table'-tag and the type error was gone. I hope this can help somebody.
