### ISSUE TITLE
InfiniteScroll - with variable sized elements

### ISSUE THREAD

**Issue by droizman** [cubiq/iscroll#607]
I have a product feed similar to a pinterest where each item may have a different height, depending on the contents.  

It looks like Infinite Scroll does not dynamically detect the height of the element but I want to verify that is the case.  

If that is the case, any recommendations for how to achieve this?  I can code it up myself and post back to this message, but it would be great to get pointed in the right direction :)

**Comment by roundrobin** [comment]
@droizman Do you might have a standalone demo of your approach? I am pretty new to iScroll and I am very interested in your solution. A stripped down demo showing variable heights would be super helpful

**Comment by avisone** [comment]
i need this funtionality..........can anyone reply?

**Comment by jgluhov** [comment]
Does not work...

**Comment by jgluhov** [comment]
droizman could you give your version of iscroll ??? if it's completed ?

**Comment by avisone** [comment]
nice work man, i can use this concept to make it work. Thanks

**Comment by avisone** [comment]
i made this to work perfectly, for infinite content this is the best solution. abhi2664@gmail.com

**Comment by avisone** [comment]
no i cannot give it to u for free
