### ISSUE TITLE
scroll in another scroll - StopPropagation

### ISSUE THREAD

**Issue by Lulun10** [cubiq/iscroll#616]
Hi,

I have a problem,
I want to do a horizontal scroll (scroll1) in another horizontal scroll (scroll2).
Then, when I scroll the scroll2 I would like the Scroll2 does not move.

In iScroll 4 I was like this :
<code>
scroll = new iScroll("menu",{
		bounce: true,
		hScrollbar: false,
		vScrollbar: false,
		hScroll: false,
        onBeforeScrollStart: function (e) {
            var target = e.target;
            while (target.nodeType != 1) target = target.parentNode;
            if (target.tagName != 'SELECT' && target.tagName != 'INPUT' && target.tagName != 'TEXTAREA')
                e.preventDefault();
			e.stopPropagation();
        }
});
</code>

I don't know how to to this in iscroll 5.
I test "preventDefault", "scroll.on('beforeScrollStart', function(e){" but e.stopPropagation provoke an error.

Do you have an idea ?

(Sorry for my bad english)

**Comment by yinzSE** [comment]
+1
I got same problem

**Comment by cubiq** [comment]
I believe you are looking for the eventPassthrough option. Have a look at the demo https://github.com/cubiq/iscroll/tree/master/demos/event-passthrough

**Comment by yinzSE** [comment]
@cubiq thanks much

I solved problem as below
```
div#a-iscroll
  div.a-scroller
    // ...
    div#b-iscroll
      div.b-scroller
```
```
// init
aIScroll = new IScroll('#a-iscroll')
bIScroll = new IScroll('#b-iscroll')

bIScroll.on('beforeScrollStart', () => {
  aIScroll.iscroll.enabled = false
})

bIScroll.on('scrollEnd', () => {
  aIScroll.iscroll.enabled = true
})
```
