### ISSUE TITLE
Direction with mousewheel

### ISSUE THREAD

**Issue by izifortune** [cubiq/iscroll#652]
Hello, i was wondering why directionX and directionY seems not to work when using the mousewheel, they work only if you click/tap on the list.
If this is the default behaviour there's a way to get the direction of the scroll when using the mousewheel?

**Comment by trakout** [comment]
+1, same issue. Using iscroll-probe v5.1.3.

**Comment by trakout** [comment]
Update: Solved it. Inside the `_wheel: function (e) {` function, below the following lines:

`newX = this.x + Math.round(this.hasHorizontalScroll ? wheelDeltaX : 0);`
`newY = this.y + Math.round(this.hasVerticalScroll ? wheelDeltaY : 0);`

..insert the following two lines:

`this.directionX = wheelDeltaX > 0 ? -1 : wheelDeltaX < 0 ? 1 : 0; `
`this.directionY = wheelDeltaY > 0 ? -1 : wheelDeltaY < 0 ? 1 : 0;`

**Comment by jonathanheilmann** [comment]
+1 for this solution

**Comment by sculove** [comment]
I merged. thank you very much.
