### ISSUE TITLE
Fixed the missing-item-problem

### ISSUE THREAD

**Issue by Mephiztopheles** [cubiq/iscroll#731]
If u want to see my code, jsut wirte me and i will send you the whole js so u can see if my work is good and u can merge it into your app

**Comment by hetalv985** [comment]
I am working on integrating the infinite scroll into our mobile app. I am facing the same issue that the infinite scroller does not stop loading when there are no more elements available. I see that you have a solution developed for this. Would it be possible for you to share the code (whole js file)? Thanks.

**Comment by davidpfahler** [comment]
@Mephiztopheles If this fix of yours is iscroll related, please submit a pull request.
