### ISSUE TITLE
IScroll prevents HTML5 input type range from working

### ISSUE THREAD

**Issue by mluis** [cubiq/iscroll#732]
When embedding an input type range as content to scroll, that input doesn't work. It seems that IScroll prevents it from sliding.
![screen shot 2014-06-17 at 16 28 03](https://cloud.githubusercontent.com/assets/162384/3303193/661d90ec-f63c-11e3-812a-cdd0899a02ba.png)

**Comment by AlexGach** [comment]
Thanks for sharing the solution
