### ISSUE TITLE
avoid using onload="loaded()"> in the body tag

### ISSUE THREAD

**Issue by native-apps** [cubiq/iscroll#733]
Sorry, i'm not a jquery expert, but i'm trying to move this function to solely my <script></script> tags for my wordpress theme for the sake of avoiding using onload="loaded()" inside my body tag. I've read that this is also not a good practice. Would you be able to help me with moving that function to my <script> tags and not the body tag?

**Comment by mikem33** [comment]
I think you can name your function, for example scroller() and initialize it in window load event.
```
jQuery(window).load( function() {
    scroller();
});
var myScroll;

function scroller() {
    myScroll = new IScroll('#wrapper', {
        eventPassthrough: true,
        scrollX: true,
        scrollY: false,
        preventDefault: false,
        scrollbars: true,
        mouseWheel: true,
        interactiveScrollbars: true,
        shrinkScrollbars: 'scale',
        fadeScrollbars: true,
   });
}
```
