### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined (if you enable scrollbars)

### ISSUE THREAD

**Issue by jerczu** [cubiq/iscroll#768]
If I have hideScrollbar:false and scrollbars:true as an option and after a resize I reinitialise the iScroll (so I destroy it first and reinitialise it) with the same option I get this error if the scrollbars are true as soon as I switch this options to false the error doesn't happen but it does every time if I have the scrollbar options enabled as above.

**Comment by rosko** [comment]
Hello. I got the same error when it tries to continue scrolling on inertia after destroying iScroll.

**Comment by benlwilliams** [comment]
nim23's fix worked for me as well.

**Comment by mtuzinskiy** [comment]
In case if someone is facing this issue and don't want to modify the source code of the lib, you can do this before the destroy:
```
scroll._events = {};
```

**Comment by rwhepburn** [comment]
+1 Experienced the same issue when using iScroll with Knockout JS.

**Comment by sculove** [comment]
@nim23 thank you. I merged on master branch.
