### ISSUE TITLE
Really jumpy on iOS 6 Safari

### ISSUE THREAD

**Issue by thdoan** [cubiq/iscroll#769]
The horizontal scrolling is not smooth at all on my iPhone 4 using Safari (still on iOS 6). Here are the options I'm using:

`
{  
  eventPassthrough: true,
  mouseWheel: true,
  scrollX: true,
  scrollY: false
}
`

Ironically, it is super smooth on an Android phone using Chrome. What are the optimum options to have smooth scrolling in stock Safari for iPhone 4?

**Comment by bandhavya** [comment]
But using useTransition: false, android scroll is reacting after sometime and not immediately on scroll
