### ISSUE TITLE
Missing AMD support

### ISSUE THREAD

**Issue by Razinsky** [cubiq/iscroll#774]
Would it be possible to add support for AMD such as
<pre>if (typeof module !== 'undefined' && module.exports) {
	module.exports = IScroll;
} else if (typeof define === 'function' && define.amd) {
	define(function(){ return IScroll; });
} else {
	window['IScroll'] = IScroll;
}</pre>

Thanks.

**Comment by jshthornton** [comment]
+1

**Comment by czerasz** [comment]
+1

**Comment by FrendEr** [comment]
+1 haha
