### ISSUE TITLE
Set scroll during momentum

### ISSUE THREAD

**Issue by henit** [cubiq/iscroll#834]
When the scroll is in "momentum mode" after releasing the mouse pointer in movement (Chrome 39, Windows 7 browser), I try to scroll up using .scrollBy(0, -3000). So it is supposed to scroll up 3000 pixels, and then continue the momentum motion until it is complete.

I experience that the scroll area keep moving, but the element has not actually scrolled. The same code works when the scrollTo is triggered while not in a momentum movement. Unfortuently, I don't have any code example to show. I use the following options:
    useTransform: true
    useTransition: true
    momentum: true
    probeType: 3
the rest is default.

**Comment by henit** [comment]
I still hope for an answer on the momentum-scroll bug. I made a simple jsfiddle for recreating the bug. 

http://jsfiddle.net/gto3z4ue/

You can do this:

1. Click the modify-button. 100 lines of text is added above the existing content in the red box, but the modify function scroll opposite to compensate, so the view remain on the same position, only the scrollbar move.

2. Initiate a momentum-movement by clicking/taping, moving and releasing so the momentum movement slow down the scroll towards a stop. After releasing, while the momentum movement is still going, click the modify-button. Then the new content appear, but it seems iScroll does not handle the scroll command, so the view does not remain in the same position, and complete the rest of the momentum-movement over completely different content.

This is a big problem in the application I am developing, so I really hope there is a possible solution, by using some other configs, or possibly fixing the bug so the scroll command is applied during momentum movement aswell.

**Comment by henit** [comment]
I also tried to change

myScroll.scrollBy(0, -1600);

to

myScroll.scrollTo(0, myScroll.y - 1600);

and the same thing happens. So both scrollBy and scrollTo fail to scroll during momentum, contrary to what the documentation states ("Granular control over the scroll position, even during momentum. You can always get and set the x,y coordinates of the scroller.")

**Comment by henit** [comment]
Problem fixed. Removed use of iScroll in the application.

**Comment by endoplasmic** [comment]
I'm here because of this issue. Being able to cancel the momentum animation programmatically is essential for what I'm trying to do.

There *must* be a way to trigger what happens when I tap the scroller during this time via code.
