### ISSUE TITLE
SWIPE for iOS

### ISSUE THREAD

**Issue by uncledent** [cubiq/iscroll#852]
Hello, we want to use iScroll with Backerframework (http://www.bakerframework.com). It works wonderfully, but there is only one problem, which is crucial. Bakerframework needs swipe event to switch to the next/prev page. Iscroll blocks it. How can we enable this event in iScroll? Is it possible? Thank you in advance!

**Comment by uncledent** [comment]
Sorry, hadn't get the eventPassthrough: 'horizontal', option. It is working more then fine! Thank u!

**Comment by rovissi** [comment]
Hi uncledent my e-mail: rovissi@gmail.com
after your return we erase this
