### ISSUE TITLE
Has iscroll stopped being maintained?

### ISSUE THREAD

**Issue by chchrist** [cubiq/iscroll#865]
Hello, 
The last commit was on  Sep 19, 2014...
And there are lots of pull requests.
Are there any other contributors who can take charge if the original author is not able to work on it?

**Comment by cubiq** [comment]
I'm working on iScroll TNG (The Next Generation :) ). New codebase. Easier to expand. Easier to use. Easier to develop with.

**Comment by DPr00f** [comment]
Was that an auto response? Or just great timing? O.o

**Comment by cubiq** [comment]
I follow all the bug reports and use your input for the next iScroll version. Unfortunately I don't have time to also maintain the previous versions.

**Comment by DPr00f** [comment]
That's fair enough but could you add some user(s) to keep track on what's going on with the old (actual) version?
There's stuff that we would love to see merged in but they seem lost in time.

**Comment by cubiq** [comment]
the few people that gave their availability haven't actually helped much. If anyone is seriously interested are more than willing to give write permissions

**Comment by chchrist** [comment]
Could you give us an update on the new one? About the existing should we fork privately and then pick the pull requests we are interested?

**Comment by cubiq** [comment]
if there's interest we could set up a discussion on which bugs really need to be fixed (and which PR to merge) in the current version before considering it "closed" and replaced by the new one.

**Comment by dt1973** [comment]
Thanks for the response @cubiq, and for the time and effort you put into making our apps scrollable.

Once my app starts making money you can expect a major donation.

Have a great weekend!

**Comment by jhnns** [comment]
On this occasion I'd like to say thank you for your great work @cubiq :)

**Comment by chchrist** [comment]
This plugin is great and thank you for all the great effort. I just got worried that it is discontinued.
We should have this discussion @cubiq

**Comment by cubiq** [comment]
don't know which would be the best place to discuss about this. I could send a message to all PR, but that seems a bit overkill

**Comment by ray007** [comment]
Maybe start a TNG branch (or new repo) so we can see where you intend to go?

**Comment by cubiq** [comment]
yeah I'll push a "dev" branch soon

**Comment by justnorris** [comment]
@cubiq Just curious -  do you have a date in mind when you'd want to release iScroll TNG ?

**Comment by cubiq** [comment]
I'll be working on it starting next week

**Comment by fdelin** [comment]
Although start date is not necessarily the best indication of an end date! That said, iscroll is still the best solution I've found out there even a year later. I know a lot of us really can't wait to get our hands on a revamped version.

**Comment by jhnns** [comment]
Ditto

**Comment by ray007** [comment]
Any news on the `dev` branch you were talking about?

**Comment by sshams** [comment]
Recently i came across an issue where I had to implement over 100 elements in an iScroll inside an iOS embedded app, unfortunately the app was crashing, not because of iScroll but limited allocation of memory by the iOS for the app. 

I worked out the issue by removing iScroll, creating 8 LI's, displaying 4 and appending/prepending the other 4 on swipe based on the direction of swipe. Of course it's not so smooth the way iScroll works.

I've a suggestion based on how the native scroll of iOS works, it dynamically re-uses elements that goes beyond the screen, re-inserts, asks the delegate code what content to insert, and passes events to our code in case of touch/click so we know which item was clicked.

I think there's a need for a different approach for iScroll based on the above suggestion. Thanks.

**Comment by sculove** [comment]
@sshams we make eg.infiniteGrid.
the infiniteGrid supports recycle elements and responsive layout.

- DEMO : http://codepen.io/egjs/pen/zvrbap
- repository : https://github.com/naver/egjs

**Comment by justnorris** [comment]
@cubiq It's been a year since "next week" :). Any news? Is iScroll dead ?

**Comment by cubiq** [comment]
last commit is 3 days old... iscroll 6 is worked in spare time
