### ISSUE TITLE
click: true and tap: true, bug ?

### ISSUE THREAD

**Issue by angelru** [cubiq/iscroll#878]
Hello, i have a problem, tap: true and click: true, click twice in android 4.3  4.2. 4.1.
in android 4.4 works well. how can I fix it?

**Comment by laziel** [comment]
Hi. Isn't it same with #674 #361 ?

**Comment by angelru** [comment]
yes! I had not seen it

**Comment by davidpfahler** [comment]
Closing because this issue is a duplicate of #361.
