### ISSUE TITLE
Zepto tap and isrcoll tap event of conflict events

### ISSUE THREAD

**Issue by xuetian120** [cubiq/iscroll#908]
Zepto tap and isrcoll tap event of conflict events

**Comment by davidpfahler** [comment]
@xuetian120 Please specify what the conflict is. I will reopen as soon as we have more information on the issue.

**Comment by TheJson** [comment]
Hello...I'm using zeptojs and iscroll5...I noted that I have a problem...the tap event of zeptojs is in conflict with the tap event of iscroll5...so I have a div wrapper (iscroll on this div) and in this I have a div scroller...now in my div scroller there are one input type email and when I tap on input the keyboard opens in rigth way but when I close it the input has the focus so if I click on any section the device open automatically the keyboard...How can fix it?Is There a solution???is there anyone that have my same problem? Thanks!
