### ISSUE TITLE
Android performance is considerably worse than iOS

### ISSUE THREAD

**Issue by Dragooon** [cubiq/iscroll#91]
When comparing my Galaxy S (Running Gingerbread 2.3.4 with stock samsung browser) to Safari mobile in iPod Touch 3G, the performance is much worse. Even in itself it feels very jerky and laggy, whereas in iTouch it is quite close to a native experience.

Regardless, I'd like to thank you for your efforts and the project is great.

**Comment by oliguo** [comment]
I'm having the same issue.if content contain more img and text,it will be slow

**Comment by huanxijiuhao** [comment]
@oliguo I have the same issue like you. How do you solve this problem?

**Comment by kaansoral** [comment]
which phone is it slow on?

I haven't noticed a considerable slowness on S4/UIWebView, and my content has a lot of CSS3

**Comment by bandhavya** [comment]
Slowness in android mobile is observed.
whereas iOS works fast using useTransition: false
