### ISSUE TITLE
.snapTo() issue

### ISSUE THREAD

**Issue by azev** [cubiq/iscroll#915]
The option `.SnapTo()` should center the element at the middle of the view, not at the top.

**Comment by davidpfahler** [comment]
@azev Thanks for your feedback. This is not a bug report, but a feature request. You would like to have the ability to snap to an element and have the element end up centered in the view. @cubiq may take this into account when he creates the next version of iscroll.

**Comment by azev** [comment]
"You would like to have the ability to snap to an element and have the element end up centered in the view"
Exactly!Thanks
