### ISSUE TITLE
destroy() does not cancel resizeTimeout

### ISSUE THREAD

**Issue by unilynx** [cubiq/iscroll#924]
I'm seeing javascript errors if I destroy an iscroll in my window onResize handler:

Uncaught TypeError: Cannot read property 'length' of undefined_indicatorsMap 
@ iscroll.js?c=DToLACPt4QE:975(anonymous function) 
@ iscroll.js?c=DToLACPt4QE:1008IScroll._execEvent 
@ iscroll.js?c=DToLACPt4QE:739IScroll.refresh 
@ iscroll.js?c=DToLACPt4QE:698(anonymous function) 
@ iscroll.js?c=DToLACPt4QE:624

From what I can tell, one of the destroy handlers should have cleared resizeTimeout.

**Comment by sculove** [comment]
I agree! 
I fix it

Look at this PR 
https://github.com/cubiq/iscroll/pull/950
