### ISSUE TITLE
Momentum, snap-to and one item at a time

### ISSUE THREAD

**Issue by plchampigny** [cubiq/iscroll#96]
Hi,

In my application, I had to fake the iPad springboard swipe paging behavior. So if I swipe with high momentum, it would swipe to next page (and snap to) and if i scroll to 1/3 of the screen, it would come back to it's initial place (in springboard it's 50%).

So my problem: if i put the momentum ON -> it will swipe on 2-3 page depending of the momentum and then snap-to. And the second problem: it would be nice to set the snapThreshold to a percent of the size of the item to scroll.

I solved the problem by modifying your code:

In the function _end:

I added your momentum calculation ouside the "if (duration < 300 && that.options.momentum) {" bracket

and i changed the snapping verification to add the absolute of the distance in X and Y of the momentum to the distance moved. 

So now in my application I can do momentum swipe one item at a time.

Hope you will integrate this feature in your project!

Pierre-Luc

**Comment by chenqiushi** [comment]
> snap for one page/item at a time!  

Could anyone tell me is this feature supported in latest version ?  

Thanks so much.
