### ISSUE TITLE
mouseWheel:true prevent other mouse handlers to catch events

### ISSUE THREAD

**Issue by alvarotrigo** [cubiq/iscroll#980]
It seems that when I use the option `mouseWheel :true` my other mouse wheel handlers won't receive any event.

[My event being fired](http://jsfiddle.net/Lehqx9ne/6/)

[My event not being fired](http://jsfiddle.net/Lehqx9ne/7/)

**Comment by sculove** [comment]
iscroll is preventing on wheel event.
```js
_wheel: function (e) {
		if ( !this.enabled ) {
			return;
		}

		e.preventDefault();
		e.stopPropagation();
```
I will check it.

**Comment by sculove** [comment]
I fix it on master branch. please wait for next release.

**Comment by alvarotrigo** [comment]
Thanks @sculove, hopefully this will allow iScroll.js to finally be used in fullpage.js.

**Comment by alvarotrigo** [comment]
Why did you close it? Will it be merged?

**Comment by sculove** [comment]
@alvarotrigo yes. I merged

**Comment by alvarotrigo** [comment]
Great! Thanks!

**Comment by alvarotrigo** [comment]
This problem doesn't seem to be solved for IE. (any version)
Can we re-open it?

**Comment by alvarotrigo** [comment]
`e.preventDefault();` should be also removed. 
Not quite sure why is there or if it will break anything, but removing it makes it work.

**Comment by alvarotrigo** [comment]
I would like to add iScroll.js as a dependency for [fullPage.js](https://github.com/alvarotrigo/fullPage.js)  but I won't be able to do it until this issue gets fixed. 

Meanwhile I'll be forced to provide a forked version of iScroll.js and therefore I won't be able to add the official iScroll.js as a dependency in neither bower or npm. 
Neither would I be able to link to the official iScroll.js for people to download it.
