### ISSUE TITLE
iscroll-infinite: Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by xueqingxiao** [cubiq/iscroll#992]
``` js
this.options.dataset.call(this, 0, this.options.cacheSize); // here dataset is undefined
```

below is my config:

``` js
new IScroll('.m-scroll-wrapper', {
          mouseWheel: true,
          infiniteElements: '.m-scroller p',
          cacheSize: 1000
        });
```

**Comment by xueqingxiao** [comment]
iscroll 5 infinite version

**Comment by tafelito** [comment]
idk if you solved your issue, in case u didn't, u have to set the dataset when setting up the iscroll instance

`myScroll = new IScroll('#wrapper', {
mouseWheel: true,
infiniteElements: '#scroller .row',
//infiniteLimit: 2000,
dataset: requestData,
dataFiller: updateContent,
cacheSize: 1000
});`
